In [1]:
import numpy as np

In [2]:
# Array Creations

In [3]:
arr = np.array([1,2,3,4])

print(arr)

[1 2 3 4]


In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)

print(a * b)

print(a - b)

print(a / b)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [5]:
arr = np.array([10,20,30,40])

print(arr[1:3])

[20 30]


In [6]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
print(arr.shape)

(2, 3)


In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# 📌 6. Mathematical Functions

In [11]:
np.mean(arr)

3.5

In [12]:
np.max(arr)

6

In [13]:
np.sum(arr)

21

In [14]:
np.min(arr)

1

In [15]:
np.std(arr)

1.707825127659933

In [16]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# Array Operations

In [20]:
np.add(a,b)

array([5, 7, 9])

In [21]:
np.multiply(a,b)

array([ 4, 10, 18])

In [22]:
np.subtract(a, b)

array([-3, -3, -3])

In [23]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [24]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [25]:
np.power(a,b)

array([  1,  32, 729])

In [26]:
np.mod(a,b)

array([1, 2, 3])

In [27]:
arr = np.array([1,2,3,4,5,6])

print(arr)

print(arr[0])

print(arr[1:3])

[1 2 3 4 5 6]
1
[2 3]


In [28]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr = np.array([[10,20,30],[40,50,60]])

print(arr)

[[10 20 30]
 [40 50 60]]


In [30]:
arr.shape

(2, 3)

In [31]:
arr.ndim

2

In [32]:
arr.size

6

In [33]:
arr.dtype

dtype('int32')

In [34]:
# 5. Broadcasting (Important Concept)

In [35]:
a = np.array([1,2,3,4])
b = 2

print(a * b)

[2 4 6 8]


In [36]:
a = np.array([1,2,3])

b = np.array([4,5,6])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [37]:
arr = np.array([1,2,3,4])

np.split(arr,2)

[array([1, 2]), array([3, 4])]

In [38]:
# Random Numbers

In [39]:
np.random.rand(2,2)


array([[0.86862302, 0.4905991 ],
       [0.62895991, 0.46334203]])

In [40]:
np.random.randint(1,10,(2,3))

array([[1, 5, 8],
       [2, 9, 7]])

In [41]:
# Copy vs View (IMPORTANT)

In [42]:
a = np.array([10,20,30,40])
b = a.copy()

In [43]:
b = a.view()

In [44]:
arr = np.array([1,2,3,4,5])

print(arr[arr > 2])

[3 4 5]


In [45]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
arr = np.array([1,2,3,4])

In [47]:
np.max(arr)

4

In [48]:
np.min(arr)

1

In [49]:
np.mean(arr)

2.5

In [50]:
np.sum(arr)

10

In [51]:
np.std(arr)

1.118033988749895